branches:
  only:
    - master

language: php

php:
  - 5.3

before_script:
  - "sh bin/setup_extensions.sh"

script: "phpunit tests/ || cat /var/log/memcached.log"

notifications:
  irc:
    - "irc.freenode.org#fluxbb"
